package com.tobibur.journey.ui.theme.colors

import androidx.compose.ui.graphics.Color
import com.tobibur.journey.ui.theme.JourneyColorScheme

object RedColorScheme : JourneyColorScheme() {
    override val Seed = Color(0xFFEF5350)

    override val PrimaryLight = Color(0xFFB4282B)
    override val OnPrimaryLight = Color(0xFFFFF7F6)
    override val PrimaryContainerLight = Color(0xFFF95A56)
    override val OnPrimaryContainerLight = Color(0xFF290002)
    override val InversePrimaryLight = Color(0xFFF95A56)
    override val SecondaryLight = Color(0xFF785754)
    override val OnSecondaryLight = Color(0xFFFFF7F6)
    override val SecondaryContainerLight = Color(0xFFFFDAD7)
    override val OnSecondaryContainerLight = Color(0xFF694A47)
    override val TertiaryLight = Color(0xFF7C5829)
    override val OnTertiaryLight = Color(0xFFFFF7F3)
    override val TertiaryContainerLight = Color(0xFFD7A871)
    override val OnTertiaryContainerLight = Color(0xFF472A00)
    override val BackgroundLight = Color(0xFFFFF8F7)
    override val OnBackgroundLight = Color(0xFF3E2F2E)
    override val SurfaceLight = Color(0xFFFFF8F7)
    override val OnSurfaceLight = Color(0xFF3E2F2E)
    override val SurfaceVariantLight = Color(0xFFF6DDDB)
    override val OnSurfaceVariantLight = Color(0xFF6D5B59)
    override val SurfaceTintLight = Color(0xFFB4282B)
    override val InverseSurfaceLight = Color(0xFF130C0C)
    override val InverseOnSurfaceLight = Color(0xFFA79A99)
    override val ErrorLight = Color(0xFFA73B21)
    override val OnErrorLight = Color(0xFFFFF7F6)
    override val ErrorContainerLight = Color(0xFFFD795A)
    override val OnErrorContainerLight = Color(0xFF6E1400)
    override val OutlineLight = Color(0xFF8A7674)
    override val OutlineVariantLight = Color(0xFFC3ADAB)
    override val ScrimLight = Color(0xFF000000)
    override val SurfaceBrightLight = Color(0xFFFFF8F7)
    override val SurfaceContainerLight = Color(0xFFFEE9E7)
    override val SurfaceContainerHighLight = Color(0xFFF9E3E1)
    override val SurfaceContainerHighestLight = Color(0xFFF6DDDB)
    override val SurfaceContainerLowLight = Color(0xFFFFF0EF)
    override val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    override val SurfaceDimLight = Color(0xFFEDD5D2)

    override val PrimaryDark = Color(0xFFFFB3AE)
    override val OnPrimaryDark = Color(0xFF860011)
    override val PrimaryContainerDark = Color(0xFFA21920)
    override val OnPrimaryContainerDark = Color(0xFFFFDBD8)
    override val InversePrimaryDark = Color(0xFFB4282B)
    override val SecondaryDark = Color(0xFFE7BDB9)
    override val OnSecondaryDark = Color(0xFF563937)
    override val SecondaryContainerDark = Color(0xFF503432)
    override val OnSecondaryContainerDark = Color(0xFFDFB6B2)
    override val TertiaryDark = Color(0xFFE5B67E)
    override val OnTertiaryDark = Color(0xFF533406)
    override val TertiaryContainerDark = Color(0xFFD7A871)
    override val OnTertiaryContainerDark = Color(0xFF472A00)
    override val BackgroundDark = Color(0xFF130C0C)
    override val OnBackgroundDark = Color(0xFFF9E0DE)
    override val SurfaceDark = Color(0xFF130C0C)
    override val OnSurfaceDark = Color(0xFFF9E0DE)
    override val SurfaceVariantDark = Color(0xFF302221)
    override val OnSurfaceVariantDark = Color(0xFFBCA6A4)
    override val SurfaceTintDark = Color(0xFFFFB3AE)
    override val InverseSurfaceDark = Color(0xFFFFF8F7)
    override val InverseOnSurfaceDark = Color(0xFF5D5352)
    override val ErrorDark = Color(0xFFF97758)
    override val OnErrorDark = Color(0xFF450900)
    override val ErrorContainerDark = Color(0xFF85230A)
    override val OnErrorContainerDark = Color(0xFFFF9B82)
    override val OutlineDark = Color(0xFF84716F)
    override val OutlineVariantDark = Color(0xFF544443)
    override val ScrimDark = Color(0xFF000000)
    override val SurfaceBrightDark = Color(0xFF372927)
    override val SurfaceContainerDark = Color(0xFF221716)
    override val SurfaceContainerHighDark = Color(0xFF281D1C)
    override val SurfaceContainerHighestDark = Color(0xFF302221)
    override val SurfaceContainerLowDark = Color(0xFF1A1110)
    override val SurfaceContainerLowestDark = Color(0xFF000000)
    override val SurfaceDimDark = Color(0xFF130C0C)

    override val PrimaryFixed = Color(0xFFF95A56)
    override val PrimaryFixedDim = Color(0xFFE74D4B)
    override val OnPrimaryFixed = Color(0xFF000000)
    override val OnPrimaryFixedVariant = Color(0xFF420004)
    override val SecondaryFixed = Color(0xFFFFDAD7)
    override val SecondaryFixedDim = Color(0xFFF5CAC7)
    override val OnSecondaryFixed = Color(0xFF553836)
    override val OnSecondaryFixedVariant = Color(0xFF745351)
    override val TertiaryFixed = Color(0xFFD7A871)
    override val TertiaryFixedDim = Color(0xFFC89B65)
    override val OnTertiaryFixed = Color(0xFF251400)
    override val OnTertiaryFixedVariant = Color(0xFF513305)
}