package com.tobibur.journey.ui.theme

import androidx.compose.ui.graphics.Color

open class JourneyColorScheme {

    open val Seed = Color(0xFFFFBDC7)

    // Light theme colors
    open val PrimaryLight = Color(0xFF835059)
    open val OnPrimaryLight = Color(0xFFFFFFFF)
    open val PrimaryContainerLight = Color(0xFFFFD9DE)
    open val OnPrimaryContainerLight = Color(0xFF683942)
    open val InversePrimaryLight = Color(0xFFF7B5BF)
    open val SecondaryLight = Color(0xFF75565B)
    open val OnSecondaryLight = Color(0xFFFFFFFF)
    open val SecondaryContainerLight = Color(0xFFFFD9DE)
    open val OnSecondaryContainerLight = Color(0xFF5C3F44)
    open val TertiaryLight = Color(0xFF795831)
    open val OnTertiaryLight = Color(0xFFFFFFFF)
    open val TertiaryContainerLight = Color(0xFFFFDDBA)
    open val OnTertiaryContainerLight = Color(0xFF5F411C)
    open val BackgroundLight = Color(0xFFFFF8F7)
    open val OnBackgroundLight = Color(0xFF22191B)
    open val SurfaceLight = Color(0xFFFFF8F7)
    open val OnSurfaceLight = Color(0xFF22191B)
    open val SurfaceVariantLight = Color(0xFFF3DDDF)
    open val OnSurfaceVariantLight = Color(0xFF524345)
    open val SurfaceTintLight = Color(0xFF835059)
    open val InverseSurfaceLight = Color(0xFF382E2F)
    open val InverseOnSurfaceLight = Color(0xFFFEEDEE)
    open val ErrorLight = Color(0xFFBA1A1A)
    open val OnErrorLight = Color(0xFFFFFFFF)
    open val ErrorContainerLight = Color(0xFFFFDAD6)
    open val OnErrorContainerLight = Color(0xFF93000A)
    open val OutlineLight = Color(0xFF847375)
    open val OutlineVariantLight = Color(0xFFD6C2C4)
    open val ScrimLight = Color(0xFF000000)
    open val SurfaceBrightLight = Color(0xFFFFF8F7)
    open val SurfaceContainerLight = Color(0xFFFBEAEB)
    open val SurfaceContainerHighLight = Color(0xFFF5E4E5)
    open val SurfaceContainerHighestLight = Color(0xFFF0DEE0)
    open val SurfaceContainerLowLight = Color(0xFFFFF0F1)
    open val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
    open val SurfaceDimLight = Color(0xFFE7D6D7)

    // Dark theme colors
    open val PrimaryDark = Color(0xFFF7B5BF)
    open val OnPrimaryDark = Color(0xFF4D232C)
    open val PrimaryContainerDark = Color(0xFF683942)
    open val OnPrimaryContainerDark = Color(0xFFFFD9DE)
    open val InversePrimaryDark = Color(0xFF835059)
    open val SecondaryDark = Color(0xFFE4BDC2)
    open val OnSecondaryDark = Color(0xFF43292E)
    open val SecondaryContainerDark = Color(0xFF5C3F44)
    open val OnSecondaryContainerDark = Color(0xFFFFD9DE)
    open val TertiaryDark = Color(0xFFEBBF90)
    open val OnTertiaryDark = Color(0xFF452B08)
    open val TertiaryContainerDark = Color(0xFF5F411C)
    open val OnTertiaryContainerDark = Color(0xFFFFDDBA)
    open val BackgroundDark = Color(0xFF191112)
    open val OnBackgroundDark = Color(0xFFF0DEE0)
    open val SurfaceDark = Color(0xFF191112)
    open val OnSurfaceDark = Color(0xFFF0DEE0)
    open val SurfaceVariantDark = Color(0xFF524345)
    open val OnSurfaceVariantDark = Color(0xFFD6C2C4)
    open val SurfaceTintDark = Color(0xFFF7B5BF)
    open val InverseSurfaceDark = Color(0xFFF0DEE0)
    open val InverseOnSurfaceDark = Color(0xFF382E2F)
    open val ErrorDark = Color(0xFFFFB4AB)
    open val OnErrorDark = Color(0xFF690005)
    open val ErrorContainerDark = Color(0xFF93000A)
    open val OnErrorContainerDark = Color(0xFFFFDAD6)
    open val OutlineDark = Color(0xFF9F8C8E)
    open val OutlineVariantDark = Color(0xFF524345)
    open val ScrimDark = Color(0xFF000000)
    open val SurfaceBrightDark = Color(0xFF413738)
    open val SurfaceContainerDark = Color(0xFF261D1E)
    open val SurfaceContainerHighDark = Color(0xFF312829)
    open val SurfaceContainerHighestDark = Color(0xFF3C3233)
    open val SurfaceContainerLowDark = Color(0xFF22191B)
    open val SurfaceContainerLowestDark = Color(0xFF140C0D)
    open val SurfaceDimDark = Color(0xFF191112)

    // Fixed colors (same for light and dark)
    open val PrimaryFixed = Color(0xFFFFD9DE)
    open val PrimaryFixedDim = Color(0xFFF7B5BF)
    open val OnPrimaryFixed = Color(0xFF340F17)
    open val OnPrimaryFixedVariant = Color(0xFF683942)
    open val SecondaryFixed = Color(0xFFFFD9DE)
    open val SecondaryFixedDim = Color(0xFFE4BDC2)
    open val OnSecondaryFixed = Color(0xFF2C1519)
    open val OnSecondaryFixedVariant = Color(0xFF5C3F44)
    open val TertiaryFixed = Color(0xFFFFDDBA)
    open val TertiaryFixedDim = Color(0xFFEBBF90)
    open val OnTertiaryFixed = Color(0xFF2B1700)
    open val OnTertiaryFixedVariant = Color(0xFF5F411C)
}
